kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vmware-vsphere-csi-driver-node-binding
  namespace: openshift-cluster-csi-drivers
subjects:
  - kind: ServiceAccount
    name: vmware-vsphere-csi-driver-node-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: Role
  name: vmware-vsphere-csi-driver-node-role
  apiGroup: rbac.authorization.k8s.io
