# Grant controller access to leases
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vmware-vsphere-csi-driver-lease-leader-election
  namespace: openshift-cluster-csi-drivers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vmware-vsphere-csi-driver-lease-leader-election
subjects:
- kind: ServiceAccount
  name: vmware-vsphere-csi-driver-controller-sa
  namespace: openshift-cluster-csi-drivers
