kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vsphere-csi-webhook-role-binding
  namespace: openshift-cluster-csi-drivers
subjects:
  - kind: ServiceAccount
    name: vmware-vsphere-csi-driver-webhook-sa
    namespace: openshift-cluster-csi-drivers
roleRef:
  kind: Role
  name: vmware-vsphere-csi-driver-webhook-role
  apiGroup: rbac.authorization.k8s.io
