apiVersion: v1
kind: Service
metadata:
  name: vmware-vsphere-csi-driver-webhook-svc
  namespace: openshift-cluster-csi-drivers
  labels:
    app: vmware-vsphere-csi-driver-webhook
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: vmware-vsphere-csi-driver-webhook-secret
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  ports:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    app: vmware-vsphere-csi-driver-webhook
  type: ClusterIP
