apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    # This label ensures that the OpenShift Certificate Authority bundle
    # is added to the ConfigMap.
    config.openshift.io/inject-trusted-cabundle: "true"
  name: vmware-vsphere-csi-driver-trusted-ca-bundle
  namespace: openshift-cluster-csi-drivers
