apiVersion: v1
kind: Secret
metadata:
  namespace: openshift-cluster-csi-drivers
  name: vsphere-csi-config-secret
# rest of the cloud-config is populated via operator and
# csi-cloud-config.ini is used as a basis.
data:
  cloud.conf: ""
